export const calendarActionTypes = {
    SET_MONTH: 'SET_MONTH',
    SET_YEAR: 'SET_YEAR',
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    SET_SELECTED_DATES: 'SET_SELECTED_DATES',
    SET_DATE_CLICKED_OPEN_EVENT: 'SET_DATE_CLICKED_OPEN_EVENT',
    SET_SHOW_EVENTS_ON_DATE: 'SET_SHOW_EVENTS_ON_DATE',
    SET_EVENTS_TO_STATE: 'SET_EVENTS_TO_STATE',
    SET_HOMEPAGE_DATA: 'SET_HOMEPAGE_DATA',

}